In [1]:
import numpy as np

# Introduction to Numpy
    * Numpy is a Python package and it stands for numerical python
    * Fundamental package for numnerical computations in Python
    * Support N-dimensional array objects that can be used for processing multidimensional data

# Array
    * An array is a data structure that stores values of same data type
    * Lists can contain values corresponding to different data types
    * Array in python can only contain values corresponding to same data type

# NumPy Array
    * A numpy array is a grid of values, all of the same type, and is indexed  by a tuple of non-negative integer
    * The number of dimensions is the rank of the array
    * The shape of an array is a tuple of integers giving the size of the array along each dimension

# Creation of array

In [2]:
my_list = [1,2,3,4,5,6]
print(my_list)

[1, 2, 3, 4, 5, 6]


* To create numpy array, we first need to import numpy package

In [3]:
import numpy as np

In [4]:
array = np.array(my_list, dtype = int)
print(array)

[1 2 3 4 5 6]


In [5]:
print(type(array))
print(len(array))
print(array.ndim)
print(array.shape)

<class 'numpy.ndarray'>
6
1
(6,)


In [7]:
array2 = array.reshape(3,2)
print(array2)
print(array2.shape)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [8]:
array3 = array.reshape(3,-1)
print(array3)
print(array3.shape)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [10]:
array_1 = array.reshape(-1,1)
print(array_1)
print(array_1.shape)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)


# Initializing numpy arrays from nested python list

In [11]:
my_list2 = [1,2,3,4,5]
my_list3 = [2,3,4,5,6]
my_list4 = [9,7,6,8,9]
mul_arr = np.array([my_list2,my_list3,my_list4])
print(mul_arr)
print(mul_arr.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [9 7 6 8 9]]
(3, 5)


In [12]:
mul_arr.reshape(-1,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [2],
       [3],
       [4],
       [5],
       [6],
       [9],
       [7],
       [6],
       [8],
       [9]])

In [13]:
mul_arr.reshape(1,15)

array([[1, 2, 3, 4, 5, 2, 3, 4, 5, 6, 9, 7, 6, 8, 9]])

# NumPy-Attributes

In [14]:
a = np.array([[1,2,3],[4,5,6]])
print(a.shape)

(2, 3)


# reshaping the ndarray

In [15]:
a.shape = (3,2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [16]:
r = range(24)
print(r)

range(0, 24)


In [17]:
# an array of evenly spaced number
a = np.arange(24)
print(a)
print(a.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
1


In [18]:
# Reshaping the array 'a'
b = a.reshape(6,4,1)
print(b)

[[[ 0]
  [ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]
  [ 7]]

 [[ 8]
  [ 9]
  [10]
  [11]]

 [[12]
  [13]
  [14]
  [15]]

 [[16]
  [17]
  [18]
  [19]]

 [[20]
  [21]
  [22]
  [23]]]


# NumPy Arthemetic operation


In [19]:
x = np.array([[1,2],[3,4]],dtype = np.float64)
y = np.array([[5,6],[7,8]],dtype = np.float64)
print(x)
print(y)

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]


# numpy.add() - performs elementwise addition between two arrays


In [20]:
# Syntax: numpy.add(arr_1,arr_2)

In [22]:
print(x+y)
print(np.add(x,y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


# numpy.subtract() - performs elementwise subtraction between two arrays

In [23]:
# Syntax: numpy.subtract(arr_1,arr_2)

In [24]:
print(x-y)
print(np.subtract(x,y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


# numpy.multiply() - performs elementwise multiplication between two arrays

In [25]:
# Syntax: numpy.multiply(arr1,arr2)

In [28]:
print(x*y)
print(np.multiply(x,y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [29]:
print(x.dot(y))

[[19. 22.]
 [43. 50.]]


In [30]:
print(np.dot(x,y))

[[19. 22.]
 [43. 50.]]


In [31]:
print(x/y)
print(np.divide(x,y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


* Function Name                        Description
    * np.add(): Add arguments element wise
    * np.subtract() : Subtract argument, element-wise
    * np.multiply() : Multiply arguments element-wise
    * np.divide() :  Return a true, division of the input, elemnent wise
    * np.logaddexp() : Logarithm of the sum of exponentions of the input in base-2
    * np.true_divide() : 
    * np.negative: Numerical negative, element-wise
    * np.positive: Numerical positive, element-wise
    * np.power() : First array element raised to powers from second array, elememtn-wise
    * np.remainder: return element-wise remainder of division
    * np.mod: return element-wisae remainder of division

# np.sum() - returns sum of all array elements or sum of all array elements over a given axis
* Syntax: np.sum(array,axis)

In [32]:
print(x)

[[1. 2.]
 [3. 4.]]


In [33]:
print(np.sum(x)) # compute overall sum (axis=None)

10.0


In [35]:
print(np.sum(x,axis=0)) # Computer sum of each column

[4. 6.]


In [37]:
print(np.sum(x,axis=1)) # computer sum of each row

[3. 7.]


# END OF SCRIPT